stateDiagram-v2
  state "К выполнению" as Todo
  state "В работе" as Work
  state "Ревью" as Review
  state "Готово" as Done
  [*] --> Todo
  Todo --> Work: взять в работу
  Work --> Review: pull request
  Review --> Done: смёржено
  Done --> [*]
